spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: notificationuser
    password: notificationpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

kafka:
  bootstrap-servers: localhost:9092
  topics:
    notifications-in: notifications-out
    notifications-sent: notifications-sent

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"